### ISSUE TITLE
Verify E-mail Fails

### ISSUE THREAD

**Issue by ZenHarbinger** [VirginiaTech/virginiatech.github.io#1]
Attempt to apply, my e-mail verification response comes back as:

{errorMessage=Cannot find module 'request-promise', errorType=Error, stackTrace=["require (internal\/module.js:12:17)","Object. (\/var\/task\/handler.js:3:10)","Module._compile (module.js:409:26)","Object.Module._extensions..js (module.js:416:10)","Module.load (module.js:343:32)","Function.Module._load (module.js:300:12)","Module.require (module.js:353:17)"]}

**Comment by forteddyt** [comment]
Thanks for bringing that to our attention. I'll disable the Apply to Organization button until this issue's been resolved. It should be up and working within the next 2 hours or so.

**Comment by forteddyt** [comment]
The entire process should be fully functioning again and the button has be re-enabled.
Per policy, you'll need to go through the process again. Sorry for any inconveniences. Thanks again for telling us about it, Zen!

**Comment by ZenHarbinger** [comment]
Oops, I clicked on the link on the email previously sent and accepted the invite.  Do you need me to re do it?

**Comment by forteddyt** [comment]
No, don't worry about it
